### ISSUE TITLE
Replacement plan references unknown parameter

### ISSUE THREAD

**Issue by jamadaha** [jamadaha/P10#111]
Domain: barman
Meta action:
```
(:action $dynamicmacro_pre_2
:parameters (?h - hand ?c - container ?ix2 - ingredient ?dx4 - dispenser)
:precondition 
(and
(ontable ?c)
(handempty ?h)
(dispenses ?dx4 ?ix2)
(empty ?c)
(used ?c ?ix2)
)
:effect 
(and
(not (ontable ?c))
(holding ?h ?c)
(contains ?c ?ix2)

(not (empty ?c))
(not (handempty ?h))
)
)
```

[macro2.txt](https://github.com/jamadaha/P10/files/15385213/macro2.txt)
[macro2_replacement.txt](https://github.com/jamadaha/P10/files/15385217/macro2_replacement.txt)

Specifically this step:
(refill-shot ?1 ?2 ?0 ?O0 ?3)
Where ?3 is referenced, but the macro has no such parameter.

**Comment by kris701** [comment]
Check if the new `macro-cache-check-delay` argument can fix this
